### ISSUE TITLE
Appearance in theme list is strange, 2 versions of theme appear

### ISSUE THREAD

**Issue by apurvaashok** [pressbooks/pressbooks-donham#2]
### Prerequisites

_Check the boxes below by changing them from `[ ]` to `[x]`._

* [ ] Can you reproduce the behavior you wish to address with [all plugins except Pressbooks deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/), the latest version of [Pressbooks Book](http://github.com/pressbooks/pressbooks-book/releases/latest/), the latest version of [this book theme](http://github.com/pressbooks/pressbooks-donham/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Are you experiencing the issue while using this book theme?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks-donham) to see if your bug or enhancement is already listed?

### Description

In the Appearance Menu, 2 versions of the Donham theme appear. One is the regular theme, the other "active theme" has the following error message: "The active theme is broken. Reverting to the default theme." 

### Steps to Reproduce

Not Applicable.

**Expected behavior:** Go to themes list and see theme active as normal, can export files.

**Actual behavior:** Error when exporting: “Error: The export failed. See logs for more details.” See screenshot of themes lists:
![screen shot 2017-07-13 at 12 18 22](https://user-images.githubusercontent.com/28899196/28176754-878fcfa2-67c6-11e7-846d-431d11d37722.png)

![screen shot 2017-07-13 at 12 18 29](https://user-images.githubusercontent.com/28899196/28176757-88e56e2a-67c6-11e7-8b03-fcc93b5ad0df.png)

### System Information

Book Theme: Donham 1.6.1
Pressbooks: 4.0.0
WordPress: 4.8
PHP: 5.6.30

**Comment by greatislander** [comment]
If this happens, just activate the working version of the theme. This should have been handled by the 3.x to 4.0 upgrade.
